export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const FETCH_ALL_BUSINESSES = "FETCH_ALL_BUSINESSES";
export const ADD_BUSINESS = "ADD_BUSINESS";
export const SET_BUSINESS_DETAILS = "SET_BUSINESS_DETAILS";
export const FETCH_BUSINESS_REVIEWS = "FETCH_BUSINESS_REVIEWS";
export const ADD_BUSINESS_REVIEW = "ADD_BUSINESS_REVIEW";
export const ADD_TO_FAVOURITE = "ADD_TO_FAVOURITE";
export const REMOVE_FROM_FAVOURITE = "REMOVE_FROM_FAVOURITE";
export const FOLLOW_USER = "FOLLOW_USER";
export const UNFOLLOW_USER = "UNFOLLOW_USER";
export const UPVOTE_BUSINESS = "UPVOTE_BUSINESS";
export const DOWNVOTE_BUSINESS = "DOWNVOTE_BUSINESS";
export const FETCH_USERS_PROFILE = "FETCH_USERS_PROFILE";
export const MODIFY_BUSINESS = "MODIFY_BUSINESS";
export const DEFAULT_BUSINESS_IMAGE = "DEFAULT_BUSINESS_IMAGE";
export const DELETE_PICTURE = "DELETE_PICTURE";
export const FETCH_GALLERIES = "FETCH_GALLERIES";

